### ISSUE TITLE
Support for sub stream 2

### ISSUE THREAD

**Issue by tane64** [rroller/dahua#94] opened 2021-09-23 21:54 UTC
3841 camera connected to NVR 4208 works fine with 4K support.  Please also add sub stream 2. what is supported by new cameras. 

Other fine working cameras also connected to the NVR
4239 (best camera from Dahua)
4131
5442

**Comment by Margriko** [comment] 2021-09-28 07:13
Possible duplicate of #36.
Just to add, It would be great to have a selection the second stream added, I use the second one in HA because it supports widescreen resolution. The first substream is disabled on my cameras. If I enable substream checkbox in this integration, the entity is created, but no video is shown because it is linked to substream 1.

**Comment by rroller** [comment] 2021-12-26 21:05
This is now released in https://github.com/rroller/dahua/releases/tag/0.9.29

All streams are added by default now by querying the device to see how many streams are supported then a camera entity is created for each stream. NOTE: It even creates a camera entity for disabled streams. You can just remove the entity from HA if you don't want it.

Please let me know if you have any issues.

**Closed by rroller** 2021-12-26 21:05 UTC
