### ISSUE TITLE
"User input malformed" error

### ISSUE THREAD

**Issue by PhilippeRaven** [rroller/dahua#110] opened 2021-11-07 10:26 UTC
Version of the custom_component : 0.9.24 installed from HACS directly.

Describe the bug : 
When adding the Dahua integration into my HA, I use those settings for my VTO2202 and when I validate the configuration, I got the "User input malformed" error, can't understand why.
Here are my settings : 

user : admin
pass : mypass
IP : 192.168.30.20
port : 80
RTSP port : 554
Channel : 0
RTSP stream : Main
Events : AlarmLocal, SmartMotion*, FaceDetection, AlarmOutput.

Debug log : 
No logs to provide.

Thanks

**Comment by kcm117** [comment] 2021-11-11 02:57
Same issue here, not sure what logs to check for more information.

**Comment by PhilippeRaven** [comment] 2021-11-11 18:08
> Same issue here, not sure what logs to check for more information.
> 
> Version: Dahua v 0.9.24
> 
> **Configuration:**
> 
> > Username*: admin
> > password*: [my password]
> > Address*:  192.168.0.235
> > Port*: 80
> > RTSP Port*: 554
> > Channel: 0
> > RTSP Streams: Main
> > Events: VideoMotion, SmartMotionHuman (Multi selected)
> 
> **Results**:
> 
> Error: "User input malformed"
> 
> I have noticed that when the "Events" are not selected, the setup proceeds without error:
> 
> > Username*: admin
> > password*: [my password]
> > Address*:  192.168.0.235
> > Port*: 80
> > RTSP Port*: 554
> > Channel: 0
> > RTSP Streams: Main
> > Events: [None Selected]
> 
> **Results:**
> 
> Success - No Error Message

I got a "workaround" if I can name this like that. You just change nothing to the pre-selected events, and it works. So you got some wrong sensors that are not use (depending of your model), but at least you can add your camera to HA through this integration. 

But still, this bug should be fixed :)

**Comment by Lepelot** [comment] 2021-11-13 20:51
Same Dahua camera, same problem ("User input malformed") however, in my case, if I don't select "events", I get this other message: Error: Username, Password, or Address is wrong.
Not sure what to do next. 
I don't know if it's related, but I am also unable to get ring button notifications on my phone either.  The video and audio streams are  fine on the phone and on the recorder (Blue Iris).

**Comment by Lepelot** [comment] 2021-11-14 18:16
Good progress today: I am now also able to start the integration if I don't select any event in the configuration.

**Comment by rroller** [comment] 2021-11-14 18:19
Just wanted to say I’m around but busy with other things. Sorry for the lack of updates here!

**Comment by rroller** [comment] 2021-12-24 19:06
I'm trying to reproduce this, so far I can't. Any other info on how to repro?

**Comment by rroller** [comment] 2021-12-24 19:14
I just tried with 4 different camera models and can't repro. Can you try the latest version of 0.9.26? I doubt that's it. Also are you on a new version of HA? I'm on a new version and don't have an issue.

If you can find more logs that would be helpful.

**Comment by rroller** [comment] 2022-01-01 01:44
FYI 0.9.31 is released with a bug fix for parsing VTO events.

**Comment by rroller** [comment] 2022-01-01 19:20
Not hearing anything back on this and I can't reproduce it. I did find a bug with parsing that's fixed in 0.9.31. Please reopen if you continue to have this problem.

**Closed by rroller** 2022-01-01 19:20 UTC
