### ISSUE TITLE
Issue with channel +1 in camera.py

### ISSUE THREAD

**Issue by fokcuk** [rroller/dahua#67] opened 2021-08-08 12:21 UTC
Was reported a number of times in different threads.
camera.py has a "channel + 1" in a number of places, which causes issues when adding channel from NVR

**Comment by rroller** [comment] 2021-08-08 15:38
When you add the integration, what does the model show as in HA?

I'm trying to figure out how I can programmatically determine if it's an NVR or not. Seems the single cams need the +1.

**Comment by fokcuk** [comment] 2021-08-08 15:46
you already have a check for channel when adding one. For NVR one would add each channel. I think for single camera its channel 0, so you add +1. But if channel above 0, you dont need to add anything

**Comment by fokcuk** [comment] 2021-08-08 15:48
under device info it just has "31"

**Comment by rroller** [comment] 2021-08-14 17:11
Thanks, sorry for the late replies.

I've released https://github.com/rroller/dahua/releases/tag/0.9.14 which will only increment the channel number by 1 if the channel number is 0. I don't know if this is correct as I don't have an NVR to test with it. Can you please give it a try and let me know how it goes?

**Comment by voskuh** [comment] 2021-08-28 20:11
Thanks for your efforts to try to implement NVR and DVR.

I don't think this change is fixing the problem. When I add channel 0 and channel 1, they both are linked to the same cam. I think the issue is caused by different versions of the api. 
For older devices it's not necessary to increment the channel number with 1 to get the right snapshots and streams. For newer devices it's necessary to increment.

In the past I had an older DVR. When I installed a new one I had to increment the channel numbers with 1 in home assistant. I've 5 cameras connected to the DVR. To get the first camera stream:
Old device: rtsp://username:password@ipaddress:port/cam/realmonitor?channel=0&subtype=0
New device: rtsp://username:password@ipaddress:port/cam/realmonitor?channel=1&subtype=0
Maybe, it's an idea to request /cgi-bin/snapshot.cgi?channel=0 first. When there is a proper response, then it isn't necessary to increment the channel number.  When the request fails, then increment the channel number. 

Response to /cgi-bin/snapshot.cgi?channel=0 with new device. The request fails because it's necessary to increment the channel number. 
```
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Connection: close
< Set-Cookie:secure; HttpOnly
< Content-type: text/plain;charset=utf-8
< Content-Length: 21
<
Error
Bad Request!
```

**Comment by rroller** [comment] 2021-08-29 17:20
@voskuh what model number shows up when you add your device on the device info section? As an example here is one of mine...

![image](https://user-images.githubusercontent.com/445655/131259255-23cfa562-508b-4858-b0dd-97b43461f161.png)

Also, I added a check as you suggest above and released it in 0.9.19.

Do you mind giving that a try?

**Comment by voskuh** [comment] 2021-08-29 19:30
Works as expected for my device. 

Device info
XVR5108C-X
door Dahua
Firmware: 4.000.0000002.11,build:2019-08-29 21:01:40

**Comment by rroller** [comment] 2021-08-30 01:01
Thanks. Resolving this one.

**Closed by rroller** 2021-08-30 01:01 UTC
