### ISSUE TITLE
IVS event not triggering Home Assistant event.

### ISSUE THREAD

**Issue by DDDaveBell** [rroller/dahua#11] opened 2021-06-17 02:59 UTC
I have a fresh install of HA (2021.6.4) with the latest Dahua integration installed.
IVS is set up on two cameras (different models) and the CrosslineEvent is ticked for both.
I can see the events occurring using a cut down version of the original Johnny le Trois python script that subscribes to the camera's events.
However, the events do not appear in HA.
I can listen to "dahua" events in HA using the Developer Tools, and no triggers are reported.
There are no errors or warnings reported by HA in the home-assistant.log..

**Comment by rroller** [comment] 2021-06-17 03:04
Thanks for the info. I'll try to dig into this tonight.

**Comment by DDDRelic** [comment] 2021-06-17 04:25
Just restarted HA and trolling through the logs, found:
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/dahua/__init__.py:333
Integration: Dahua (documentation, issues)
First occurred: 2:45:42 PM (1 occurrences)
Last logged: 2:45:42 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/dahua/__init__.py", line 352, in async_reload_entry
    await async_unload_entry(hass, entry)
  File "/home/homeassistant/.homeassistant/custom_components/dahua/__init__.py", line 333, in async_unload_entry
    coordinator = hass.data[DOMAIN][entry.entry_id]
KeyError: '39a26d9371896845786cdc2d267505fe'

Also found:
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:164
First occurred: 2:38:19 PM (10 occurrences)
Last logged: 2:45:44 PM

Error setting up entry 5MF50Z6BPDC4693 for camera
Error setting up entry Driveway for binary_sensor
Error setting up entry Driveway for switch
Error setting up entry Driveway for light
Error setting up entry Driveway for camera
Traceback (most recent call last):
  File "/home/homeassistant/.local/lib/python3.8/site-packages/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.local/lib/python3.8/site-packages/homeassistant/components/binary_sensor/__init__.py", line 141, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/home/homeassistant/.local/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by DDDRelic** [comment] 2021-06-17 04:27
Possible that the last error is caused by my renaming "5MF50Z6BPDC4693" to "Driveway" in the Dahua integration?

**Comment by rroller** [comment] 2021-06-17 05:09
@DDDRelic looks like that is it. By renaming my cam I'm experiencing the same as you. I'll work through this bug and get it fixed, sorry for the issues.

As a temp work around, delete the cam and add it back. I'll keep this issue open to track the fix.

**Comment by rroller** [comment] 2021-06-18 21:34
@DDDRelic I've added the binary sensor for cross line detection (tripwire) in the latest version of the integration. 

See this for more details - https://github.com/rroller/dahua/issues/13

**Comment by rroller** [comment] 2021-06-19 23:10
I'll close this issue out as the requested events are now supported as long as you selected them when you configured the camera. If you didn't, readd the camera and select the events. I'll create a new issue for supporting renames.

**Closed by rroller** 2021-06-19 23:10 UTC

**Comment by DDDaveBell** [comment] 2021-06-20 20:25
Renaming is all good now thanks.
