### ISSUE TITLE
Upcoming issue with Home Assistant 2025.1

### ISSUE THREAD

**Issue by TheSpoon98** [rroller/dahua#334] opened 2024-02-08 13:17 UTC
Camera (<class 'custom_components.dahua.camera.DahuaCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>

https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Issue pasted per the HA 2024.2 logs.

**Comment by andyfrei** [comment] 2024-02-11 07:18
Logger: homeassistant.components.camera
Source: helpers/deprecation.py:205
Integration: Kamera (documentation, issues)
First occurred: 07:57:29 (2 occurrences)
Last logged: 07:57:29

SUPPORT_STREAM was used from dahua, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.STREAM instead, please create a bug report at https://github.com/rroller/dahua/issues

**Comment by tomlut** [comment] 2024-02-25 04:21
Duplicate of https://github.com/rroller/dahua/issues/328

**Comment by rroller** [comment] 2024-05-04 19:57
Fixed by merging [adutchak](https://github.com/adutchak)'s PR and released in 0.9.52
https://github.com/rroller/dahua/releases/tag/0.9.52

**Closed by rroller** 2024-05-04 19:57 UTC
