### ISSUE TITLE
Error "object has no attribute 'async_config_entry_first_refresh'"

### ISSUE THREAD

**Issue by DDDaveBell** [rroller/dahua#5] opened 2021-06-13 22:54 UTC
Just installed the component using HACS, configured one camera and found no entities or devices were created.
The following error was in the HA log:

Logger: homeassistant.config_entries
Source: custom_components/dahua/__init__.py:69
First occurred: 10:42:21 AM (1 occurrences)
Last logged: 10:42:21 AM

Error setting up entry DahuaRearDeckCamera for dahua
Traceback (most recent call last):
  File "/home/homeassistant/.local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/dahua/__init__.py", line 69, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
AttributeError: 'DahuaDataUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'

I am using Home Assistant version: 2021.1.4, frontend version: 20201229.1

**Comment by rroller** [comment] 2021-06-13 23:03
What is the model of the camera?

**Comment by DDDaveBell** [comment] 2021-06-13 23:08
The camera is a Dahua IPC-T5241TM-AS

**Comment by rroller** [comment] 2021-06-13 23:18
Thanks. It's a little hard to debug this because I don't have that model. Do you know which firmware version you are on?

Does the API work at all? You can try to load the general configuration by replacing IP_ADDRESS with the IP address of your cam. It'll prompt you for your username and password...
http://ip_address/cgi-bin/configManager.cgi?action=getConfig&name=General

**Comment by DDDaveBell** [comment] 2021-06-13 23:22
The API works OK, I currently have a script running based on the Jonny le Trois code.
It returns the events OK.
I ran the API command, the output is:
table.General.LocalNo=8
table.General.LockLoginEnable=true
table.General.LockLoginTimes=5
table.General.LoginFailLockTime=300
table.General.MachineName=5FC60A2BF1C2798
table.General.MaxOnlineTime=3600

**Comment by DDDaveBell** [comment] 2021-06-13 23:23
Camera Firmware is:V2.800.15OG004.0.R, Build Date: 2020-10-19

**Comment by rroller** [comment] 2021-06-13 23:25
Thanks. Struggling to figure out how I can debug this without having the actual hardware.

Can you try to enable debug logging and see if any additional logs are shown? You might need to completely remove the cam from HA and add it back.

This is how you'd enable debug logging...
```yaml
logger:
  logs:
    custom_components.dahua: debug
```

Are you running a recent version of Home Assistant?

**Comment by DDDaveBell** [comment] 2021-06-13 23:28
I am using Home Assistant version: 2021.1.4, frontend version: 20201229.1

**Comment by DDDaveBell** [comment] 2021-06-13 23:35
OK, I deleted the Dahua integration.
Added the logger to configuration.yaml and restarted HA.
Re-installed the Dahua integration and set up the camera.
Same result.
Where is the log stored so I can send it?

**Comment by rroller** [comment] 2021-06-13 23:38
It'll be in the same logs location as your regular home assistant logs. I'm not sure where your logs might be. It all depends how you install HA.

**Comment by DDDaveBell** [comment] 2021-06-13 23:47
OK, I found home-assistant.log but it is 16MBytes so I'll excise out the dahua related info, will take a mo.

**Comment by DDDaveBell** [comment] 2021-06-14 00:04
I have pulled out any lines referencing "dahua", and any lines in the vicinity that looked remotely cvonnected.
Not sure that this adds anything more.
2021-06-14 11:31:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for dahua which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-06-14 11:31:39 DEBUG (MainThread) [custom_components.hacs] <Integration rroller/dahua> Getting repository information
2021-06-14 11:31:39 DEBUG (MainThread) [custom_components.hacs] <Integration rroller/dahua> Running checks against 0.5.0
2021-06-14 11:32:41 INFO (MainThread) [homeassistant.setup] Setting up dahua
2021-06-14 11:32:41 INFO (MainThread) [homeassistant.setup] Setup of domain dahua took 0.0 seconds
2021-06-14 11:32:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 5FB60A2BD1C2718 for dahua
Traceback (most recent call last):
  File "/home/homeassistant/.local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/homeassistant/.homeassistant/custom_components/dahua/__init__.py", line 69, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
AttributeError: 'DahuaDataUpdateCoordinator' object has no attribute 'async_config_entry_first_refresh'
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=dahua>
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Sending {"id": 3, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "dahua"}, "origin": "LOCAL", "time_fired": "2021-06-13T23:32:41.492984+00:00", "context": {"id": "6fcc1ab7570c85ba2f6ed35b34caf3ae", "parent_id": null, "user_id": null}}}
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Sending {"id": 9, "type": "event", "event": {"event_type": "component_loaded", "data": {"component": "dahua"}, "origin": "LOCAL", "time_fired": "2021-06-13T23:32:41.492984+00:00", "context": {"id": "6fcc1ab7570c85ba2f6ed35b34caf3ae", "parent_id": null, "user_id": null}}}
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Received {'type': 'subscribe_events', 'event_type': 'area_registry_updated', 'id': 265}
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Received {'type': 'config/area_registry/list', 'id': 266}
2021-06-14 11:32:41 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Sending {'id': 265, 'type': 'result', 'success': True, 'result': None}
2021-06-14 11:32:42 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [2252327216] Sending {'id': 268, 'type': 'result', 'success': True, 'result': {'resources': {'component.config.title': 'Configuration', 'component.emulated_hue.title': 'Emulated Hue', 'component.system_health.title': 'System Health', 'component.counter.title': 'Counter', 'component.person.title': 'Person', 'component.input_boolean.title': 'Input boolean', 'component.logger.title': 'Logger', 'component.zwave.title': 'Z-Wave', 'component.cloud.title': 'Home Assistant Cloud', 'component.automation.title': 'Automation', 'component.alexa.title': 'Amazon Alexa', 'component.lovelace.title': 'Lovelace', 'component.device_automation.title': 'Device Automation', 'component.scene.title': 'Scene', 'component.ssdp.title': 'Simple Service Discovery Protocol (SSDP)', 'component.climate.title': 'Climate', 'component.light.title': 'Light', 'component.group.title': 'Group', 'component.cover.title': 'Cover', 'component.tasmota.title': 'Tasmota (beta)', 'component.mqtt.title': 'MQTT', 'component.weather.title': 'Weather', 'component.zone.title': 'Zone', 'component.conversation.title': 'Conversation', 'component.updater.title': 'Updater', 'component.websocket_api.title': 'Home Assistant WebSocket API', 'component.binary_sensor.title': 'Binary sensor', 'component.hacs.title': 'HACS', 'component.ffmpeg.title': 'FFmpeg', 'component.sun.title': 'Sun', 'component.search.title': 'Search', 'component.script.title': 'Script', 'component.mqtt_statestream.title': 'MQTT Statestream', 'component.blueprint.title': 'Blueprint', 'component.switch.title': 'Switch', 'component.tag.title': 'Tag', 'component.shelly.title': 'Shelly', 'component.system_log.title': 'System Log', 'component.history.title': 'History', 'component.onboarding.title': 'Home Assistant Onboarding', 'component.webhook.title': 'Webhook', 'component.sensor.title': 'Sensor', 'component.fan.title': 'Fan', 'component.timer.title': 'Timer', 'component.dahua.title': 'Dahua', 'component.camera.title': 'Camera', 'component.input_select.title': 'Input select', 'component.api.title': 'Home Assistant API', 'component.persistent_notification.title': 'Persistent Notification', 'component.recorder.title': 'Recorder', 'component.zeroconf.title': 'Zero-configuration networking (zeroconf)', 'component.logbook.title': 'Logbook', 'component.homeassistant.title': 'Home Assistant Core Integration', 'component.frontend.title': 'Home Assistant Frontend', 'component.stream.title': 'Stream', 'component.notify.title': 'Notifications', 'component.mobile_app.title': 'Mobile App', 'component.default_config.title': 'Default Config', 'component.discovery.title': 'Discovery', 'component.input_datetime.title': 'Input datetime', 'component.auth.title': 'Auth', 'component.http.title': 'HTTP', 'component.tts.title': 'Text-to-Speech (TTS)', 'component.map.title': 'Map', 'component.met.title': 'Meteorologisk institutt (Met.no)', 'component.lock.title': 'Lock', 'component.media_source.title': 'Media Source', 'component.image.title': 'Image', 'component.input_number.title': 'Input number', 'component.input_text.title': 'Input text'}}}

**Comment by rroller** [comment] 2021-06-14 00:35
The issue is that your home assistant is too old. You need to be on 2021.4.0 or newer.

**Comment by DDDaveBell** [comment] 2021-06-14 00:43
OK, thanks for that. I will upgrade.

**Comment by rroller** [comment] 2021-06-14 14:46
Closing. Feel free to reopen if this doesn't fix the issue.

**Closed by rroller** 2021-06-14 14:46 UTC

**Comment by DDDaveBell** [comment] 2021-06-14 23:07
Just FYI, I upgraded Home Assistant (and Python) and the integration works perfectly. Thanks for your assistance.
